GET http://localhost:5000/api/todos?page=1&limit=5&priority=high&category=Shopping
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4N2I2ZGU5YzU0Y2UwNGQxYTcwOGQ1ZSIsImlhdCI6MTc1MjkxOTY0NCwiZXhwIjoxNzUzNTI0NDQ0fQ.JB5GWJL30nylzX28pu1UsUmCGBR7Gehg6bEE8qqE0Xc