    ### Request OTP to be sent to email
    POST http://localhost:5000/api/users/forgot
    Content-Type: application/json

    {
    "email": "netdark195@gmail.com"
    }

    # Expected Response (Status 200)
    # { "message": "OTP has been sent to your email." }


    ### Submit OTP and New Password for Reset
    POST http://localhost:5000/api/users/reset
    Content-Type: application/json

    {
    "email": "netdark195@gmail.com",
    "otp": "339484",
    "newPassword": "Kesava@123"
    }

    # Expected Response (Status 200)
    # { "message": "Password reset successful." }